#!/bin/bash
#
# Track startup script for Serverless (search) track.
#
# Runs on host-1 when the track starts. Expects:
#   ELASTICSEARCH_URL, ELASTICSEARCH_API_KEY (or ELASTICSEARCH_APIKEY), KIBANA_URL
# from the Instruqt connection (e.g. Elastic Cloud Serverless project).
#
# This script:
#   1. Waits for Elasticsearch to be reachable (API key auth)
#   2. Clones the workshop repo
#   3. Creates .env with Serverless credentials
#   4. Creates indices (Serverless-compatible: no number_of_shards)
#   5. Loads workshop data via bulk API (setup_workshop_data.sh)
#   6. Creates incidents and notifications indices if missing
#   7. Starts the FastAPI app
#
# No snapshot/restore — Serverless does not support snapshot APIs.
# Semantic search (ELSER): use --skip-semantic if your project doesn't have ELSER.
#

set -e

WORKSHOP_DIR="${WORKSHOP_DIR:-/workspace/workshop/elastic-workflow-workshop}"
REPO_URL="${REPO_URL:-https://github.com/elastic/elastic-workflow-workshop.git}"

# Auth: Serverless uses API key only
ELASTICSEARCH_URL="${ELASTICSEARCH_URL:?ELASTICSEARCH_URL is required for Serverless track}"
ELASTICSEARCH_API_KEY="${ELASTICSEARCH_API_KEY:-$ELASTICSEARCH_APIKEY}"
if [ -z "${ELASTICSEARCH_API_KEY}" ]; then
    echo "ERROR: ELASTICSEARCH_API_KEY or ELASTICSEARCH_APIKEY is required for Serverless"
    exit 1
fi
KIBANA_URL="${KIBANA_URL:-}"

echo "=============================================="
echo "  Workshop Startup (Serverless)"
echo "=============================================="
echo ""

es_curl() {
    curl -s -H "Authorization: ApiKey ${ELASTICSEARCH_API_KEY}" "$@"
}

# -----------------------------------------------------------------------------
# 1. Wait for Elasticsearch
# -----------------------------------------------------------------------------
echo "[1/7] Waiting for Elasticsearch..."
MAX_RETRIES=60
RETRY=0

until es_curl "${ELASTICSEARCH_URL}" -o /dev/null -w "%{http_code}" 2>/dev/null | grep -q "200"; do
    RETRY=$((RETRY + 1))
    if [ $RETRY -ge $MAX_RETRIES ]; then
        echo "  ERROR: Elasticsearch did not become ready"
        exit 1
    fi
    echo "  Waiting... (attempt ${RETRY}/${MAX_RETRIES})"
    sleep 5
done
echo "  Elasticsearch is ready."

# -----------------------------------------------------------------------------
# 2. Clone workshop repo
# -----------------------------------------------------------------------------
echo ""
echo "[2/7] Cloning workshop repository..."
if [ -d "${WORKSHOP_DIR}" ]; then
    git -C "${WORKSHOP_DIR}" pull --ff-only 2>/dev/null || true
else
    mkdir -p "$(dirname "${WORKSHOP_DIR}")"
    git clone "${REPO_URL}" "${WORKSHOP_DIR}"
fi
echo "  Repository ready."

# -----------------------------------------------------------------------------
# 3. Create .env
# -----------------------------------------------------------------------------
echo ""
echo "[3/7] Creating .env..."
cat > "${WORKSHOP_DIR}/.env" <<EOF
# Auto-generated by Instruqt startup-serverless.sh
ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
ELASTICSEARCH_API_KEY=${ELASTICSEARCH_API_KEY}
KIBANA_URL=${KIBANA_URL}
ELASTICSEARCH_VERIFY_CERTS=${ELASTICSEARCH_VERIFY_CERTS:-true}
EOF
echo "  .env written."

# -----------------------------------------------------------------------------
# 4. Create indices (Serverless-safe) and load data
# -----------------------------------------------------------------------------
echo ""
echo "[4/7] Creating indices and loading data..."
cd "${WORKSHOP_DIR}"

# No venv: es3-api-v2 images lack ensurepip / python3-venv (see lib/serverless_pydeps.sh).
INSTRUQT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/serverless_pydeps.sh
source "${INSTRUQT_DIR}/lib/serverless_pydeps.sh"

# Create indices: Serverless-compatible (--serverless omits number_of_shards etc.)
# If ELSER is not available in the project, use --skip-semantic
export ELASTICSEARCH_URL ELASTICSEARCH_API_KEY
python3 -m admin.create_indices --delete-existing --force --serverless 2>/dev/null || \
python3 -m admin.create_indices --delete-existing --force --serverless --skip-semantic

# Load data (uses data/sample or generates)
if [ ! -d "data/sample" ]; then
    mkdir -p data/sample
fi
if [ ! -f "data/sample/businesses.ndjson" ] || [ ! -f "data/sample/reviews.ndjson" ]; then
    echo "  Generating sample data..."
    python3 -m admin.generate_sample_data \
        --businesses 300 --users 1500 --reviews 8000 --output data/sample 2>/dev/null || true
fi
if [ -f "data/sample/businesses.ndjson" ]; then
    echo "  Loading data..."
    python3 -m admin.load_data \
        --businesses-file data/sample/businesses.ndjson \
        --users-file data/sample/users.ndjson \
        --reviews-file data/sample/reviews.ndjson 2>/dev/null || true
fi
echo "  Indices and data ready."

# -----------------------------------------------------------------------------
# 5. Create incidents and notifications indices (Serverless: no shard settings)
# -----------------------------------------------------------------------------
echo ""
echo "[5/7] Ensuring incidents and notifications indices exist..."

INC_MAPPING='{"mappings":{"properties":{"incident_id":{"type":"keyword"},"business_id":{"type":"keyword"},"business_name":{"type":"text","fields":{"keyword":{"type":"keyword"}}},"detected_at":{"type":"date"},"incident_type":{"type":"keyword"},"severity":{"type":"keyword"},"status":{"type":"keyword"},"review_count":{"type":"integer"},"unique_reviewers":{"type":"integer"},"avg_rating":{"type":"float"},"avg_trust_score":{"type":"float"},"time_window_minutes":{"type":"integer"},"held_review_ids":{"type":"keyword"},"flagged_user_ids":{"type":"keyword"},"summary":{"type":"text"},"assigned_to":{"type":"keyword"},"resolved_at":{"type":"date"},"resolution":{"type":"keyword"},"notes":{"type":"text"}}}}'
NOTIF_MAPPING='{"mappings":{"properties":{"notification_id":{"type":"keyword"},"notification_type":{"type":"keyword"},"recipient_type":{"type":"keyword"},"priority":{"type":"keyword"},"title":{"type":"text"},"message":{"type":"text"},"business_id":{"type":"keyword"},"incident_id":{"type":"keyword"},"created_at":{"type":"date"},"read":{"type":"boolean"},"read_at":{"type":"date"}}}}'

for index in incidents notifications; do
    if ! es_curl -o /dev/null -w "%{http_code}" "${ELASTICSEARCH_URL}/${index}" 2>/dev/null | grep -q "200"; then
        if [ "$index" = "incidents" ]; then
            es_curl -X PUT "${ELASTICSEARCH_URL}/${index}" -H "Content-Type: application/json" -d "${INC_MAPPING}" > /dev/null
        else
            es_curl -X PUT "${ELASTICSEARCH_URL}/${index}" -H "Content-Type: application/json" -d "${NOTIF_MAPPING}" > /dev/null
        fi
        echo "  Created ${index}."
    fi
done

# -----------------------------------------------------------------------------
# 6. Trust scores (optional)
# -----------------------------------------------------------------------------
echo ""
echo "[6/7] Calculating trust scores (if supported)..."
python3 -m admin.calculate_trust_scores 2>/dev/null || echo "  Skipped (optional)."

# -----------------------------------------------------------------------------
# 7. Start FastAPI app
# -----------------------------------------------------------------------------
echo ""
echo "[7/7] Starting FastAPI application..."
nohup python3 -m uvicorn app.main:app --host 0.0.0.0 --port 8000 > /tmp/app.log 2>&1 &

APP_RETRIES=0
until curl -s http://localhost:8000/health > /dev/null 2>&1; do
    APP_RETRIES=$((APP_RETRIES + 1))
    if [ $APP_RETRIES -ge 30 ]; then
        echo "  Warning: App did not become ready. Check /tmp/app.log"
        break
    fi
    sleep 2
done

echo ""
echo "=============================================="
echo "  Serverless Workshop Ready"
echo "=============================================="
echo ""
for index in businesses users reviews incidents notifications; do
    count=$(es_curl "${ELASTICSEARCH_URL}/${index}/_count" 2>/dev/null | grep -o '"count":[0-9]*' | grep -o '[0-9]*' || echo "0")
    echo "  ${index}: ${count} documents"
done
echo ""
if curl -s http://localhost:8000/health > /dev/null 2>&1; then
    echo "  App:    http://localhost:8000  (ElasticEats: /elasticeats)"
else
    echo "  App:    not ready (see /tmp/app.log)"
fi
echo "  Kibana: ${KIBANA_URL}"
echo ""
